language: node_js
node_js:
- stable
cache:
  directories: 
  - node_modules
deploy: 
  provider: npm 
  skip_cleanup: true
  email: vikingmute@gmail.com
  api_key: 
    secure: xxxxxxxxxxxxxx
  on: 
    tags: true